"use client";

import { useEffect, useState } from "react";

type Tab = "inicio" | "perfil" | "chats" | "crear" | "historial" | "ranking";
const tabs: { id: Tab; label: string; icon: string }[] = [
  { id: "inicio", label: "Inicio", icon: "⌂" }, { id: "perfil", label: "Perfil", icon: "◉" },
  { id: "chats", label: "Chats", icon: "◌" }, { id: "crear", label: "Crear", icon: "+" },
  { id: "historial", label: "Historial", icon: "↺" }, { id: "ranking", label: "Ranking", icon: "★" },
];
const courses = [
  { title: "Cálculo diferencial", owner: "Prof. Laura Méndez", detail: "Regla de la cadena · 12 retos", color: "cyan", progress: 72 },
  { title: "Pensamiento lógico", owner: "Mateo Rojas · estudiante", detail: "Sala abierta · 8 participantes", color: "pink", progress: 48 },
  { title: "Ciencias que explican", owner: "Prof. Daniel Gómez", detail: "Biología · 5 actividades nuevas", color: "lime", progress: 91 },
];
const history = ["Reto de funciones compuestas", "Mapa: ecosistemas colombianos", "Duelo de conceptos lógicos"];

export default function Home() {
  const [activeTab, setActiveTab] = useState<Tab>("inicio");
  const [online, setOnline] = useState(true);
  const [query, setQuery] = useState("");
  const [notice, setNotice] = useState("");
  useEffect(() => { setOnline(navigator.onLine); const on = () => setOnline(true); const off = () => setOnline(false); window.addEventListener("online", on); window.addEventListener("offline", off); if ("serviceWorker" in navigator) navigator.serviceWorker.register("/sw.js").catch(() => {}); return () => { window.removeEventListener("online", on); window.removeEventListener("offline", off); }; }, []);
  const showNotice = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(""), 1800); };
  const renderContent = () => {
    if (activeTab === "perfil") return <Module title="Tu perfil" eyebrow="IDENTIDAD POLIAPP"><div className="profile-card"><div className="profile-avatar">A</div><div><h2>Ana García</h2><p>Estudiante · Colegio del Futuro</p><span className="level-pill">Nivel 3 · 1.280 XP</span></div></div><div className="stat-grid"><Stat label="Racha" value="12 días" /><Stat label="Retos" value="48" /><Stat label="Ranking" value="#12" /></div><button className="primary-button full" onClick={() => showNotice("Perfil guardado localmente")}>Guardar perfil</button><button className="login-link" onClick={() => showNotice("Abriendo inicio de sesión simulado")}>Iniciar sesión / Crear usuario</button></Module>;
    if (activeTab === "chats") return <Module title="Chats y grupos" eyebrow="EN CONTACTO"><div className="chat-list">{["Cálculo I · grupo de estudio", "PoliParty · sala general", "Prof. Laura Méndez"].map((chat, index) => <button key={chat} className="chat-row" onClick={() => showNotice(`Abriendo ${chat}`)}><span className={`chat-avatar c${index}`}>{["C", "P", "L"][index]}</span><div><strong>{chat}</strong><p>{["Mañana resolvemos límites", "Nueva partida disponible", "Feedback de tu último reto"][index]}</p></div><b>{index + 1}</b></button>)}</div><button className="outline-button full" onClick={() => showNotice("Creando nuevo grupo")}>+ Crear grupo</button></Module>;
    if (activeTab === "crear") return <Module title="Crear actividad" eyebrow="PARA CREADORES"><p className="module-copy">Arma una experiencia en minutos. Elige una plantilla y deja que PoliIA te ayude a construirla.</p><div className="template-grid">{["Trivia rápida", "Mapa de ideas", "Ordena los pasos", "Duelo de conceptos"].map((item, index) => <button key={item} className="template-card" onClick={() => showNotice(`Plantilla ${item} seleccionada`)}><span>{["?", "◎", "≡", "⚡"][index]}</span><strong>{item}</strong><small>{index + 3} formatos</small></button>)}</div><button className="primary-button full" onClick={() => showNotice("Asistente IA preparado")}>Crear con PoliIA →</button></Module>;
    if (activeTab === "historial") return <Module title="Tu historial" eyebrow="PROGRESO"><div className="history-score"><span>Esta semana</span><strong>+240 XP</strong><small>18 minutos de aprendizaje · +14% vs. anterior</small></div><div className="history-list">{history.map((item, index) => <button key={item} onClick={() => showNotice(`Revisando ${item}`)}><span>{index + 1}</span><div><strong>{item}</strong><small>{index === 0 ? "Hoy · 92% correcto" : index === 1 ? "Ayer · completado" : "Lunes · 1.280 puntos"}</small></div><b>›</b></button>)}</div></Module>;
    if (activeTab === "ranking") return <Module title="Ranking PoliApp" eyebrow="COMPITE CON PROPÓSITO"><div className="ranking-hero"><span>Tu posición</span><strong>#12</strong><small>Subiste 4 lugares esta semana</small></div><div className="ranking-list">{["Santiago P.", "Valentina R.", "Ana García", "Nicolás T.", "Laura C."].map((name, index) => <div key={name} className={name === "Ana García" ? "ranking-row me" : "ranking-row"}><b>{index + 1}</b><span className="mini-avatar">{name[0]}</span><strong>{name}</strong><small>{[1820, 1640, 1280, 1190, 1100][index]} XP</small></div>)}</div></Module>;
    return <><section className="hero-panel"><div><p className="eyebrow">PÓLISCROLL · POLIAPP</p><h1>Aprende en movimiento.</h1><p className="hero-copy">Cursos, retos y grupos que siguen tu ritmo. Explora sin cuenta; guarda tu progreso cuando quieras.</p><button className="primary-button" onClick={() => showNotice("El feed personalizado estará disponible al iniciar sesión")}>Descubrir mi ruta <span>→</span></button></div><div className="hero-mark"><span>PP</span><small>POLIPARTY</small></div></section><section className="section-heading"><div><p className="eyebrow">TU CAMPUS</p><h2>Lo que estás aprendiendo</h2></div><button className="text-button" onClick={() => showNotice("Buscando cursos públicos")}>Ver todo</button></section><div className="search-box"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar cursos, grupos o temas" /></div><section className="course-feed">{courses.filter((course) => course.title.toLowerCase().includes(query.toLowerCase())).map((course) => <CourseCard key={course.title} course={course} onAction={showNotice} />)}</section><section className="section-heading"><div><p className="eyebrow">EN COMUNIDAD</p><h2>Grupos recomendados</h2></div><button className="text-button" onClick={() => showNotice("Explorando grupos cercanos")}>Explorar</button></section><div className="community-row"><div><strong>Ágora de matemáticas</strong><span>24 miembros · dirigido por Prof. Camilo</span></div><button className="outline-button" onClick={() => showNotice("Solicitud enviada")}>Unirme</button></div></>;
  };
  return <main className="app-shell"><header className="topbar"><div className="brand"><span className="brand-dot" />PoliScroll</div><div className="top-actions"><span className={`connection ${online ? "is-online" : "is-offline"}`}>{online ? "En línea" : "Sin conexión"}</span><button className="avatar-button" onClick={() => setActiveTab("perfil")}>A</button></div></header>{!online && <div className="offline-banner">Sin conexión · tu perfil y progreso guardados siguen disponibles</div>}<div className="scroll-content">{renderContent()}</div>{notice && <div className="toast">{notice}</div>}<button className="party-button" onClick={() => showNotice("PoliParty eligió: Duelo de conceptos")}><span>✦</span><b>PoliParty</b><small>jugar</small></button><nav className="bottom-nav">{tabs.map((tab) => <button key={tab.id} className={activeTab === tab.id ? "nav-item active" : "nav-item"} onClick={() => setActiveTab(tab.id)}><span>{tab.icon}</span><small>{tab.label}</small></button>)}</nav></main>;
}

function CourseCard({ course, onAction }: { course: (typeof courses)[number]; onAction: (message: string) => void }) { return <article className={`course-card ${course.color}`}><div className="card-top"><span className="course-tag">{course.color === "cyan" ? "MATEMÁTICAS" : course.color === "pink" ? "PENSAMIENTO" : "CIENCIA"}</span><span className="course-progress">{course.progress}%</span></div><h3>{course.title}</h3><p>{course.detail}</p><div className="progress-track"><i style={{ width: `${course.progress}%` }} /></div><div className="card-footer"><span>Creado por <b>{course.owner}</b></span><button onClick={() => onAction(`Abriendo ${course.title}`)}>Continuar →</button></div></article>; }
function Module({ eyebrow, title, children }: { eyebrow: string; title: string; children: React.ReactNode }) { return <section className="module-page"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{children}</section>; }
function Stat({ label, value }: { label: string; value: string }) { return <div className="stat"><strong>{value}</strong><small>{label}</small></div>; }
